name: Build version
on: workflow_dispatch

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: test version
        uses: jpbnetley/semantic-release-version@v0
        with:
          version: 0.0.1
          version-type: patch