name: Build version
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update major.minor.patch'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major


permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: debug
        run: |
         echo debug v: ${{ github.event.inputs.version }}

      - name: test version
        uses: jpbnetley/semantic-release-version@main
        id: version
        with:
          version: 0.0.1
          version-type: "${{ github.event.inputs.version }}"

      - name: new version
        run: |
          echo "new version is: ${{ steps.version.outputs.new-version }}"
